set_property SRC_FILE_INFO {cfile:{C:/Users/baiyo/Forwarding Packet/Forwarding Packet.srcs/constrs_1/new/netlist.xdc} rfile:{../../../Forwarding Packet.srcs/constrs_1/new/netlist.xdc} id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/baiyo/Forwarding Packet/Forwarding Packet.srcs/constrs_1/new/netGenRead.xdc} rfile:{../../../Forwarding Packet.srcs/constrs_1/new/netGenRead.xdc} id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports rst]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports sw_start]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 12 [get_ports o_data1]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports o_data1]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports rst]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports sw_start]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 12 [get_ports o_data]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports o_data]
